apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: kalebgmac1/ecommerce-spring-boot-microservices-inventory-service:new7
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: inventory-service-config
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: mysql_user
                  name: mysql-secrets
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql_password
                  name: mysql-secrets
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                  configMapKeyRef:
                    key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
                    name: common-config
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 8284
      targetPort: 8284
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.default.svc.cluster.local:3306/inventory_service"

